"""empty message

Revision ID: cf7e1dbfa4ea
Revises: 9a9b9e4d3c61
Create Date: 2022-10-21 21:30:56.127205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7e1dbfa4ea'
down_revision = '9a9b9e4d3c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
